### ISSUE TITLE
Tuning node-red-contib-tuya-smart-device V. 5.0.1

### ISSUE THREAD

**Issue by msillano** [vinodsr/node-red-contrib-tuya-smart-device#113]
In production, I use a little modified version of this node.

See previous post for reasons [Issue#83](https://github.com/vinodsr/node-red-contrib-tuya-smart-device/issues/83)

The modified 5.0.1 version is in attach, I hope it helps someone with the same problems as me.
[tuya-smart-device - 501-fixed.zip](https://github.com/vinodsr/node-red-contrib-tuya-smart-device/files/11241593/tuya-smart-device.-.501-fixed.zip)

Replace only the file `<nodered>\node_modules\node-red-contrib-tuya-smart-device\src\tuya-smart-device.js`

**Comment by vinodsr** [comment]
Good work @msillano . Could you please submit a Pull request ?

**Comment by msillano** [comment]
I tried to make a pull request, I hope it's the correct way.
Greetings
