### ISSUE TITLE
How to get bluetooth device through Gateway

### ISSUE THREAD

**Issue by nospam2k** [vinodsr/node-red-contrib-tuya-smart-device#120]
When I get back the ids, I get
```
{
  name: 'Gateway',
  id: GWxxxxxxxxx,
  key: 'GWxxxx',
  subDevices: [
  {
    name: 'BT Light',
    id: 'SDxxxxxxx',
    cid: 'xxxx'
  }
}
```
(ID's and keys masked. Ignore actual values)

How do I set up the node?

**Comment by msillano** [comment]
Node: only one for the gateway. NOT for subdevices.
  id: GWxxxxxxxxx,
  key: 'GWxxxx',


SET subdevice ( to gateway node):
     "payload": {
          "devId": 'xxxx',          // cid, only for subdevices (string)   
          "dps":"103",                                // DP  (string)
          "set":220                                 // BOOLEAN, INT/ENUM, STRING   
          } }

 GET subdevice ( to gateway node):
   "payload": {
          "devId": 'xxxx',          // cid, only for subdevices (string)   
          "operation":"GET",
          "dps":"103"
          } }

best regards
