### ISSUE TITLE
Weird key format?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [vinodsr/node-red-contrib-tuya-smart-device#127]
Apparently TUYA has changed something and key format is now NOT just alpha-numeric?

{
name: 'Reserve Router',
id: '31006440bcddc253e92A',
key: '.5X/3baAQaMhtI>8'
},

Above is returned by tuya-cli now, note the key is NO LONGER just alpha numeric!  Reference....

[https://github.com/TuyaAPI/cli/issues/160](url)

None of my devices that now now have the newer key format are seen by NR node now...

7 Jul 14:02:34 - [info] [tuya-smart-device:Auto View] findDevice(): Cannot find the device, re-trying...
7 Jul 14:02:34 - [info] [tuya-smart-device:Black Lasko Fan Power Control] findDevice(): Initiating the find command
7 Jul 14:02:34 - [info] [tuya-smart-device:Bond Bridge] findDevice(): Initiating the find command
7 Jul 14:02:34 - [info] [tuya-smart-device:HP LaserJet 5] findDevice(): Initiating the find command
7 Jul 14:02:35 - [info] [tuya-smart-device:Reserve Router] findDevice(): Initiating the find command
7 Jul 14:02:35 - [info] [tuya-smart-device:HP DeskJet 5650A] findDevice(): Initiating the find command
7 Jul 14:02:35 - [info] [tuya-smart-device:Storage Server] findDevice(): Initiating the find command
7 Jul 14:02:35 - [info] [tuya-smart-device:Edge Router] findDevice(): Initiating the find command
7 Jul 14:02:35 - [info] [tuya-smart-device:Eccentric] findDevice(): Initiating the find command
7 Jul 14:02:35 - [info] [tuya-smart-device:Auto View] findDevice(): Initiating the find command
7 Jul 14:02:36 - [info] [tuya-smart-device:Black Lasko Fan Power Control] findDevice(): Cannot find the device, re-trying...
7 Jul 14:02:36 - [info] [tuya-smart-device:Bond Bridge] findDevice(): Cannot find the device, re-trying...
7 Jul 14:02:36 - [info] [tuya-smart-device:HP LaserJet 5] findDevice(): Cannot find the device, re-trying...
7 Jul 14:02:37 - [info] [tuya-smart-device:Reserve Router] findDevice(): Cannot find the device, re-trying...
7 Jul 14:02:37 - [info] [tuya-smart-device:HP DeskJet 5650A] findDevice(): Cannot find the device, re-trying...
7 Jul 14:02:37 - [info] [tuya-smart-device:Storage Server] findDevice(): Cannot find the device, re-trying...
7 Jul 14:02:37 - [info] [tuya-smart-device:Edge Router] findDevice(): Cannot find the device, re-trying...
7 Jul 14:02:37 - [info] [tuya-smart-device:Eccentric] findDevice(): Cannot find the device, re-trying...

Any help greatly appreciated!

**Comment by Jibun-no-Kage** [comment]
So it never got addressed?  I provided detail and illustrative examples.

**Comment by mrmaximas** [comment]
Same issue with the special characters in the key, for example:
working key - J0;7-Br<[<zFqMmP 
bad key - .74<{0I}Z*zm$jMa
