### ISSUE TITLE
unreadable 'data' output from node

### ISSUE THREAD

**Issue by cdevereu** [vinodsr/node-red-contrib-tuya-smart-device#135]
Both my Tuya devices update their status to the node output automatically but the data is not human readable.  It looks like this: 

`{"data":"3.3\u0000\u0000\u0000\u0000\u0000\u0000I�\u0000\u0000\u0000\u0001��Y#����\u0014�?��\u0013�-�/�\u00048���[�Q�d��","deviceId":"bf5aaa50aff2a5d15cirx9","deviceName":"Oil Tank"}`

The deviceName and deviceId are fine.

Any ideas why the 'data' value is not in plain text?

[Debug window output screenshot](https://drive.google.com/file/d/16WZ_hLQLzaRaBkHpdJw2QeFcKN41qjz9/view?usp=sharing)

**Comment by cdevereu** [comment]
OK I've been reading up more from other people with similar issues and by changing the version from 3.1 to 3.3 the payload.data became readable.

**Comment by andy0983** [comment]
{data: "3.3� [�?�,�r�U�e�?�)���x�Pt(��_o�����.�O#���Irj�tu}���e�d�"
deviceId: "bf72b73d01c0d0cdfbyh6j"
deviceName: "Smart Meter "}

I changed "Tuya Protocol Version, Default : 3.1 (don't change if you are not sure)" to version 3.3 but it didn't help
please advise
