### ISSUE TITLE
Manage all Tuya devices with node-red

### ISSUE THREAD

**Issue by msillano** [vinodsr/node-red-contrib-tuya-smart-device#139]
For the development of [TuyaDAEMON](https://github.com/msillano/tuyaDAEMON) I have collected a series of information that I believe may be of general interest.

1) Most Tuya-branded devices are controllable using the [ **tuya-smart-device**](https://github.com/vinodsr/node-red-contrib-tuya-smart-device) node. All you need is the `deviceID`,  the `localKey`, and knowing the _DPs and behavior_ of the device.

2) Some devices CANNOT be controlled locally with "tuya-smart-device" because they do not have a stable WiFi connection (typically battery-operated WiFi sensors). In these cases, you can use Tuya [**'OpenAPI' via REST**](https://github.com/msillano/tuyaDAEMON/tree/main/Tuya_cloud_API) with node-red. Requires Tuya credentials and `deviceID`. Available as [TuyaDAEMON extension](https://github.com/msillano/tuyaDAEMON/blob/main/devices/_openapi/device__openapi.pdf) and also as [node-red library](https://github.com/msillano/tuyaDAEMON/tree/main/Tuya_cloud_API#node-red-tuya-openapi-v20).

3) OpenAPI can be used only in polling. It is not possible to use it for asynchronous events generated by devices (e.g. alarms). One solution is the [**HW/SW trigger**](https://github.com/msillano/tuyaDAEMON/blob/main/tuyaTRIGGER/README.md) mechanism (designed for TuyaDAEMON), which allows bidirectional communications between SmarlLife Automation and node-red. Available as [TuyaDAEMON extension](https://github.com/msillano/tuyaDAEMON/blob/main/devices/_trigger/device__trigger.pdf) and also in [lite version](https://flows.nodered.org/flow/1d03176c75458f2665c780cb56265bf3).

4) Many WiFi products without the Tuya logo are built by various manufacturers (Ikea, Philips, Siemens...) with their own APP, but were developed using Tuya. Some of these products CAN be managed with SmartLife. Unfortunately, this needs to be verified on a case-by-case basis (Tuya [communication](https://www.facebook.com/groups/330754074172355/permalink/1429527007628384/?mibextid=uJjRxr)).

5) Even some ZigBee devices produced without Tuya compatibility can be associated with a ZigBee-Tuya hub (e.g. [thermometers for Xiaomi's HomeKit APP](https://github.com/msillano/tuyaDEAMON-applications/wiki/note-4:-Gateways-and-sensors#some-known-zigbee-sensors)).

A) how to find `deviceID`, and `localKey`:
        1. `deviceID` only: in _SmartLife_, _Device Info_
        2. use [Tuya IoT Development Platform](https://developer.tuya.com/en/docs/iot/introduction-of-tuya?id=K914joffendwh) for Tuya credentials
        3. use [tuyapi_cli wizard](https://github.com/TuyaAPI/cli)
        4. use OpenAPI: 'Query Device Details' ([preferred](https://github.com/msillano/tuyaDAEMON/wiki/55.-Howto:--add-a-new-device-since-v.-2.2.4#step-1-info--dp-data-collection))

B) How to Find DPs.
       The simplest solution is to use the 'Send Properties' API ([see here](https://github.com/msillano/tuyaDAEMON/wiki/55.-Howto:--add-a-new-device-since-v.-2.2.4#step-1-info--dp-data-collection))

C) The study of the **behavior** and **quirks** of a device is greatly aided by the Log (max 7 days) present in 'Tuya Development Platform' ([see here](https://github.com/msillano/tuyaDAEMON/wiki/55.-Howto:--add-a-new-device-since-v.-2.2.4#step-3-device-behavior))

Caveat: Tuya _OpenAPI_ and _Automation_ are not very stable. Tuya occasionally changes the structure of Tuya Cloud; the latest change (June 20, 2023) made it necessary to update all Automation due to a change in the name of a condition. A change of deviceID also invalidates the Automation.

I hope this information helps someone
​

**Comment by vinodsr** [comment]
Thanks @msillano for the information
