### ISSUE TITLE
Syntax Payload get command

### ISSUE THREAD

**Issue by FreeTechNick** [vinodsr/node-red-contrib-tuya-smart-device#18]
Hi, 
the installation is fin and I can switch on and off. But I can't execute the get Command. Can you help? perhaps with an example script? Thank you.

**Comment by Biscotte312** [comment]
I've got the same problem, trying some thing, never really work. 

The best way I've found is (pass in a function node) : 

msg.payload ={
   dps : 1,
    set : null
}
return msg;

but it's not perfect, sometime it give me a wrong value

**Comment by vinodsr** [comment]
This is a know issue with Tuya library. They are near to releasing a new fix. (6.0.1) [issue](https://github.com/codetheweb/tuyapi/issues/338)

I had made an alternate fix for the same issue. but you have to be in the god mode. 

See this [issue comment](https://github.com/vinodsr/node-red-contrib-tuya-smart-device/issues/14#issuecomment-702550663)  for more details and a sample flow.

Hope this helps.
