### ISSUE TITLE
Litemate 9 W Wifi LED Lamp - Error: find() timed out 

### ISSUE THREAD

**Issue by Roselt** [vinodsr/node-red-contrib-tuya-smart-device#19]
I get an error when using the node. (I changed the device ID before posting) The node initially shows connected with the below msg.payload:

{"data":{"devId":"26701815d8bfc0eeXXX","dps":{"20":true,"21":"white","22":1000,"23":520,"24":"003a03e803e8","25":"07464602000003e803e800000000464602007803e803e80000000046460200f003e803e800000000464602003d03e803e80000000046460200ae03e803e800000000464602011303e803e800000000","26":0}},"deviceId":"26701815d8bfc0eeXXXX","deviceName":"Bulb"}

But then after a few seconds it shows this error and the it disconnects:

10/24/2020, 9:56:18 AM295487d4.17f058
msg : error
"Error: find() timed out. Is the device powered on and the ID or IP correct?"

I did test with a Connex Wifi Bulb and it works.

**Comment by vinodsr** [comment]
Are you trying to connect via node-red and app at the same time the tuya devices wont allow multiple api calls at same time. You should close the app. or any thing which accesses the device.

**Comment by Roselt** [comment]
Thank you. I tested it now with everything closed, it stays connected but I cannot control the light. I will check my flows and see if I can get it working.

**Comment by vinodsr** [comment]
Closing the issue
