### ISSUE TITLE
GET option

### ISSUE THREAD

**Issue by Nazarbayevv** [vinodsr/node-red-contrib-tuya-smart-device#20]
Hello,

How can I send GET option. I need to get power consumption.

SET option works fine

**Comment by Biscotte312** [comment]
Inject a json payload with

{"Operation":"get","schema":true}

Le dim. 1 nov. 2020 17 h 31, Nazarbayevv <notifications@github.com> a
écrit :

**Comment by Nazarbayevv** [comment]
Thaks, but any result;(

![image](https://user-images.githubusercontent.com/50654913/97846246-6495bf00-1cf6-11eb-8ded-1b903287378a.png)

**Comment by 2BAD2B007** [comment]
@Nazarbayevv  

This worked for me. Make sure that operation is all lowercase.

{"operation":"GET","schema":true};

**Comment by Nazarbayevv** [comment]
@2BAD2B007 
Oh, thanks. I receives data from one plug, but oher plug answered with error "json obj data unvalid"
![image](https://user-images.githubusercontent.com/50654913/98036540-e2ef7f80-1e22-11eb-9205-6a5f5048f76d.png)

And can you help me with dps description? I know that dps 1 - status on|off, but I want to know total consumption.  
![image](https://user-images.githubusercontent.com/50654913/98036811-4f6a7e80-1e23-11eb-949f-547238789fd6.png)

**Comment by 2BAD2B007** [comment]
I have dps["1"] = on/off, dps["19"] = current power usage, dps["20"] = voltage, and dps["18"]= current. That is all I have mapped out on my plug, and I am not sure if it differs per manufacturer. 

Are you still not able to to get data from the other plug? If not maybe you could paste your flow from node-red and I can see if I see the issue.

**Comment by Nazarbayevv** [comment]
@2BAD2B007 
Yey, I have problem with one device, It's a very easy flow

[{"id":"2d6d9de5.70cf22","type":"tab","label":"Flow 6","disabled":false,"info":""},{"id":"fc9462c7.eb583","type":"tuya-smart-device","z":"2d6d9de5.70cf22","deviceName":"tuya","deviceId":"bf55baca102901bd56ac9e","deviceKey":"988df2558fc7fdc0","x":560,"y":300,"wires":[["8072ac8a.d4d45"]]},{"id":"dcad92e2.92781","type":"inject","z":"2d6d9de5.70cf22","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"{\"operation\":\"GET\",\"schema\":true}","payloadType":"json","x":340,"y":300,"wires":[["fc9462c7.eb583"]]},{"id":"8072ac8a.d4d45","type":"debug","z":"2d6d9de5.70cf22","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":820,"y":300,"wires":[]}]

**Comment by vinodsr** [comment]
The issue with json data unvalid is a known error with some tuya devices.

You can read more about this #14  (with a workaround. may not work in all cases)

**Comment by vinodsr** [comment]
Closing the issue

**Comment by Sungtroll** [comment]
I have used many hours and over a month trying to get the get function to work but never any success until i read this post today. Please add this to the documentation immediately, it is horrible that it is missing from documentation and there is not any examples anywhere! I suggest this get the highest priority, this information does not deserve to be hidden in this closed issue.
