### ISSUE TITLE
Feature request: ability to inject device properties

### ISSUE THREAD

**Issue by formatBCE** [vinodsr/node-red-contrib-tuya-smart-device#21]
First of all - thank you for great job! This node works flawlessly, and quicker, than all other ways.

Would be great to have possibility to inject device ID, name and local key via incoming message parameters. For sure, it would make updates auto-receiving impossible, but maybe, you could create one more node, some "generic SET".

I got around 20 devices, and generic set command would speed up tuning drastically.

Thank you.

**Comment by vinodsr** [comment]
It's a good recommendation. 

It is possible to have a generic set. Let me see if it has got any issues with the tuyapi.

**Comment by vinodsr** [comment]
The feature is now available in version 1.2

**Comment by formatBCE** [comment]
That's so cool, thank you so much!
