### ISSUE TITLE
Nide is hanging often

### ISSUE THREAD

**Issue by formatBCE** [vinodsr/node-red-contrib-tuya-smart-device#24]
Hi again!
I use your node for my smart home together with Hassio, to make bulbs and switches fast and local.
I noticed, that access to devices is hanging, and they become unresponsible time to time. I have to restart/redeploy to make them working.
Is there maybe a way to restart nodes without restarting node red, or redeploying flow? 

Thank you in advance.

**Comment by vinodsr** [comment]
@formatBCE  Are you still experiencing the issue with the latest version. I am using 5 devices and still no issues. 

Please confirm .

**Comment by formatBCE** [comment]
@vinodsr  thanks for tracking this.
I moved NodeRED from hassio addon to Docker, and this issue gone.
I still have some devices reconnecting time to time, but mostly it's recovering by itself.
I suppose, it was network issues - now NodeRED is on LAN instead of WiFi.

So we can close this. Thanks!

P.S. i have around 20 devices.
