### ISSUE TITLE
Connexion error after deleting, disabling and uninstalling nodes !

### ISSUE THREAD

**Issue by juanitomaille** [vinodsr/node-red-contrib-tuya-smart-device#25]
![Capture d’écran de 2020-11-28 17-23-08](https://user-images.githubusercontent.com/44920274/100520529-7c018400-319e-11eb-8bbc-721b07b607ba.png)

I don't know how to solve that,

**Comment by vinodsr** [comment]
Fix is now available in version 1.2.1
