### ISSUE TITLE
Problems with 'GET' on all devices

### ISSUE THREAD

**Issue by msillano** [vinodsr/node-red-contrib-tuya-smart-device#28]
I have 20+ Tuya devices, like switches, sensors, ad some ZigBee devices. All devices work well in smartLife app.
I'm testing **node-red-contrib-tuya-smart.device** to do some logging and more advanced control using node-red. 
The node-red actual comportment is:

1. All devices (except some sensors) accepts "SET" commands:

Example, using a real device, a switch, the command (sets the switch on for 10 s) :
`payload: { multiple: true, data: { 1: true, 102: 10}}`
produces the answer:
`12 Dec 11:50:26 - [info] [tuya-smart-device:fe3fbeb2.ac31f] Data from device: "{"dps":{"1":true,"102":10},"t":1607770225}"`

Using a virtual device, i.e. a radiator controller and ZigBee hub, the command (sets the target temperature)
`payload: { "devId": "60a423fffeb5b90d", "dps": 103, "set": 220 }`
produces the answer:
`12 Dec 12:06:24 - [info] [tuya-smart-device:a9ea9736.7483f8] Data from device: "{"dps":"103":220},"cid":"60a423fffeb5b90d", "type":query,"t":1607771183}"`

2. I get a message also when some values are changed via smartLife, e.g.:
`12 Dec 12:14:08 - [info] [tuya-smart-device:fe3fbeb2.ac31f] Data from device: "{"dps":{"1":true},"t":1607771648}"`
`12 Dec 12:16:12 - [info] [tuya-smart-device:a9ea9736.7483f8] Data from device: "{"dps":{"101":47},"cid":"00158d00056e5022","t":1607771771}"`

3. I get also messages in case of a status change on a device, or from a sensor (without any request):
Switch countdown end:
`12 Dec 11:50:36 - [info] [tuya-smart-device:fe3fbeb2.ac31f] Data from device: "{"dps":{"1":false,"102":0},"t":1607770235}"`
Temperature from a ZigBee sensor, (about every 3600s, request by Tuya cloud?):
`12 Dec 12:14:28 - [info] [tuya-smart-device:a9ea9736.7483f8] Data from device: "{"dps":{"103":215},"cid":"60a423fffeb5b90d","t":1607771667}"`

 It sounds good, so all ok? Sorry, not really.

4. _Any 'GET' command in any device (real, virtual, ...) in any form, don't work! Always I get:_
`12 Dec 11:32:32 - [error] [tuya-smart-device:fe3fbeb2.ac31f] json obj data unvalid`

This is a big problem because I cannot read in polling any RO device data points, so some parameters are unreachable.

Maybe the problem is in TuyApi: see also issue #246 and issue #23.

Any other user has found this behavior?

Any idea for solutions?

Best regards
m.s.

**Comment by msillano** [comment]
The tuyapi ver. "6.1.1" introduces two new options:
  -    `options.nullPayloadOnJSONError = false`
  -    `options.issueGetOnConnect = true`
  
Putting both to false is a partial solution to commands (like 'GET' and 'schema') not handled by some devices and occasionally reported by the device using the misunderstandly "json obj data invalid".

The only open issue is the 'ERROR' level in case of connection loss: using `retry` this event is not an ERROR requiring programmer intervention, better if it becomes a 'warning' (errors: "Error from socket", "find() timed out. Is the device powered on and the ID or IP correct?").

-----------
But I'm using the "node-red-contrib-tuya-smart-device" ver. 1.2.1, which uses tuyapi 5.3.1.
While **waiting for an update**, my personal solution is to modify "node_modules / tuyapi / index.js" (5.3.1) so:

1) comment out lines 317-332: the complete block: _for (const packet of packets)_.
2) comment out line 404:  _this.get ();_
3) changed line 623 to:   _throw new Error (\` Rety connection: ID $ {this.device.id} \`);_ more informative.

Best regards
m.s.

**Comment by vinodsr** [comment]
Will update the latest version #33

**Comment by vinodsr** [comment]
Updated to latest 6.1.1 with the following options

options.nullPayloadOnJSONError = false
options.issueGetOnConnect = false

Please update to the 2.0.0 version of tuya-smart-device . 

Hope this fixes the issues.
