### ISSUE TITLE
can't connect at all 

### ISSUE THREAD

**Issue by malosaa** [vinodsr/node-red-contrib-tuya-smart-device#29]
first of all thanks for this awsome node-red plugin

Well i did insert the device id and key, retrieved from tuya-cli wizard

getting this error

"Error: find() timed out. Is the device powered on and the ID or IP correct?

regards

**Comment by EEAW** [comment]
same problem to me; I want to connect to a door sensor but this doesn't work. All other devices (sockets etc) are working

**Comment by birdayz** [comment]
same problem, but i have it with sockets as well. does anyone know something about the cause? it's a bit weird, on my notebook it works, but on my raspberryPI - on the same WiFi network, it does not.

**Comment by cjkring** [comment]
Same problem.   I'm happy to help isolate or test a patch.

**Comment by yasurok** [comment]
I'm experiencing exactly the same problem. But then again, I have essentially the same problem with the command line `tuya-cli get`, so it is likely a TuyAPI issue, rather than a node-red-contrib-tuya-smart-device issue.

**Comment by vinodsr** [comment]
@malosaa Can you please confirm if tuya-cli get for the same device is working ? 
```

Usage: cli get [options]

get a property on a device

Options:
  -s, --save                    save key so you can omit it for subsequent commands
  --ip <ip_addr>                ip address of device
  --id <id>                     id of device
  --key [key]                   key of device
  --dps [dps]                   property index to get (default: 1)
  -a, --all                     get all properties of a device (default: false)
  --protocol-version [version]  tuya protocol version (default: 3.1)
  -h, --help                    display help for command
```

**Comment by exemmer** [comment]
"Error: find() timed out. Is the device powered on and the ID or IP correct?"

There's no way to add the IP using this node.

I can get all my devices to work fine using tuya-cli - but have to specify the IP.

**Comment by yasurok** [comment]
>> "Error: find() timed out. Is the device powered on and the ID or IP correct?"

> There's no way to add the IP using this node.

I personally cannot confirm this entirely, but I have to report that by providing the IP address as well, I did have success with `tuya-cli get`.

**Comment by EEAW** [comment]
I tested with postman to get connection to the door sensor. The result for the GET request "Query command set supported by device" was:
"code": 2009,
    "msg": "not support this device",
    "success": false,
    "t": 1609690625115

May be this helps for analysis. The request "Get device info" gives following back:

"result": {
        "active_time": 1607528534,
        "biz_type": 18,
        "category": "qt",
        "create_time": 1607528534,
        "icon": "smart/icon/15318135469lzeqin2vrq_0.jpg",
        "id": "75364874ecfxxxxxxxxxx",
        "ip": "84.61.xxxxxxxx",
        "local_key": "6828e08d0xxxxxxxx",
        "name": "Terrassentür",
        "online": true,
        "owner_id": "322xxxx",
        "product_id": "g2l1k6zcfjjtddue",
        "product_name": "SH 510",
        "status": [],
        "sub": false,
        "time_zone": "+01:00",
        "uid": "eu1547660924990g2hIC",
        "update_time": 1607781051,
        "uuid": "75364874ecfabc97808e"
    },
    "success": true,
    "t": 1609691184275
So you can see the device is online, but not supported by TuyAPi? (the xxx are unrecognizable made by me)

**Comment by EEAW** [comment]
I opened a ticket at Tuya and got following answer: "category type "qt" of the product ID hx5ztlztij4yxxvg is wrong". 
Than I tested another (new) door sensor with 
category "mcs" and product_id "hx5ztlztij4yxxvg". 

This  one is working with postman but still NOT with node-red. The postman output is following:

"result": {
        "active_time": 1609913827,
        "biz_type": 18,
        "category": "mcs",
        "create_time": 1609913827,
        "icon": "smart/icon/1551969519maq7h6mi1l_0.jpg",
        "id": "_xxxx_",
        "ip": "84.61.141._xxx_",
        "local_key": "_xxx_",
        "name": "Küchentür",
        "online": true,
        "owner_id": "_xxx_",
        "product_id": "hx5ztlztij4yxxvg",
        "product_name": "Door Detector",
        "status": [
            {
                "code": "doorcontact_state",
                "value": false
            },
            {
                "code": "battery_state",
                "value": "high"
            }
        ],
        "sub": false,
        "time_zone": "+01:00",
        "uid": "eu1547660924990g2hIC",
        "update_time": 1609913879,
        "uuid": "_xxx_"
    },
    "success": true,
    "t": 1610195936215

In node-red I still can not connect to the decvice, the error is "find() timed out. Is the device powered on and the ID or IP correct?"
P.S. I updated the node to version 2.0.0

**Comment by msillano** [comment]
@EEAW   see [tuyapi](https://github.com/codetheweb/tuyapi):
> "TuyAPI does not support sensors due to the fact that they only connect to the network when their state changes. There are no plans to add support as it's out of scope to intercept network requests."

For that  Zigbee sensors are better:  we can talk with Zigbee gateway because it is always connected.

For wifi sensor like  'Door Detector' I found a workaround to catch  them with node-red:  see [tuyaTRIGGER](https://github.com/msillano/tuyaDAEMON/tree/main/tuyaTRIGGER)

Best regards
m.s.

**Comment by EEAW** [comment]
Thank you for response. What I not really understand: why do I get connection via postman but via node-red sensors like door sensor are not supported? Isn't postman using the same Tuyapi?

But I tried your suggestion with tuyaTRIGGER; first I had to install the SQL-DB, a bit difficult for the first time and not really necessary at the end; but I learned much new, so it's fine.

It took me a while to understand, that you use another tuya device (bridge) to save the information from the door sensor.
Great idea and it's working. Thank you!

**Comment by cw-kid** [comment]
I am also having problems with it connecting and I see these errors:

"Can't Find Device"

"Error: find() timed out. Is the device powered on and the ID or IP correct?"

I only have one device on my Tuya account a Galaxy Star Projector Light.

Sometimes it connects OK but a lot of the time it doesn't and I see that error.

Thanks

**Comment by exemmer** [comment]
Still the same issue with v3.0.1
"Error: find() timed out. Is the device powered on and the ID or IP correct?"
- using either the IP  -or-  the ID

Device is fine and controllable from CLI:
tuya-cli set --id [redacted] --key [redacted] --ip  [redacted]  --set true
- light goes on, etc,.

**Comment by exemmer** [comment]
> Still the same issue with v3.0.1
> "Error: find() timed out. Is the device powered on and the ID or IP correct?"
> 
> * using either the IP  -or-  the ID

OK - update - it works it you don't do as told on the node ("Use Device IP or Device Virtual ID (**Don't use both**)") 
....and enter BOTH the ID AND IP!

**Comment by cw-kid** [comment]
Mine is connected OK currently by just using the IP address.
