### ISSUE TITLE
Example: add example to send multiple dps in single payload

### ISSUE THREAD

**Issue by qwertangel** [vinodsr/node-red-contrib-tuya-smart-device#30]
I am trying to send multiple DPS in single payload. I tried following payload but it didn't work

`{"multiple":true,   "data": {"dps":{"20":true,"21":"white","22":1000,"23":44}}}`

any idea what could be wrong. also if you can add example in your wiki for sending multiple dps that will be helpful to others.

**Comment by msillano** [comment]
Maybe it is a device problem. 

I found many crazy behaviors in some devices and the device response for not handled commands is either 'null' or 'json obj data unvalid' without any logic.

Your payload looks ok, you can try also using string for numerical values ("44" in place of 44),  (see some examples [here](https://github.com/vinodsr/node-red-contrib-tuya-smart-device/issues/28)) .

Test also your device capability, using a single DPS.

I hope that can help you.
Best regards
m.s.

**Comment by vinodsr** [comment]
@qwertangel  can you also share the response that you are getting for this command ? 

Like what @msillano  said, some devices will not accept all commands at once. You have to give it one by one. Like turn on , change color etc. .. See if that works .  I used to do the same thing . Once the on is passed ie dps 20 then pass this command 
```
{
     multiple: true,
      data: {
          '21': "white",
       '23': 1000
     }
  }
```

Multiple option doesn't mean it will process multiple operations .. rather multiple arguments for an operation. Hope it is clear.
