### ISSUE TITLE
version 2.0.0 Error messages

### ISSUE THREAD

**Issue by msillano** [vinodsr/node-red-contrib-tuya-smart-device#35]
I'm updated to 2.0.0, thanks, very good.
I set 
````
  options.nullPayloadOnJSONError = false
  options.issueGetOnConnect = false
````
Thanks.

Now I have still a big problem: tuya-smart-device don't catch 2 errors from tuyapi, in case of device disconnection:
````
4 Jan 14:10:33 - [info] [tuya-smart-device:5a17a058.f17be] Cannot find the device, re-trying...
4 Jan 14:10:34 - [info] [tuya-smart-device:5a17a058.f17be] initiating the find command
4 Jan 14:10:44 - [error] [tuya-smart-device:5a17a058.f17be] Error: find() timed out. Is the device powered on and the ID or IP correct?
4 Jan 14:10:44 - [info] [tuya-smart-device:5a17a058.f17be] Cannot find the device, re-trying...
4 Jan 14:10:45 - [info] [tuya-smart-device:5a17a058.f17be] initiating the find command
4 Jan 14:10:55 - [error] [tuya-smart-device:5a17a058.f17be] Error: find() timed out. Is the device powered on and the ID or IP correct?
4 Jan 14:10:55 - [info] [tuya-smart-device:5a17a058.f17be] Cannot find the device, re-trying...
4 Jan 14:10:56 - [info] [tuya-smart-device:5a17a058.f17be] initiating the find command
4 Jan 14:10:59 - [info] [tuya-smart-device:5a17a058.f17be] Connected to device! 123301602cf4325eae00
````

and same for the error message:  "Error: Error from socket"

As you can see the timeout is about 10s. The unique solution is to disable the device, but it is not a solution, because in normal use some devices can stay a disconnected long time, such as some power sockets or power strips used only on request.
Some like this:
````
24 Jan 14:10:33 - [info] [tuya-smart-device:5a17a058.f17be] Cannot find the device, re-trying after XXX sec...

````
So, after study how to catch this tuyapi error (the INFO existing messages are enough) a VERY useful extension will be the ability to change at runtime the timeout (or adding a delay between tries).
A very long timeout is equivalent to a 'disable', and the user will be able to restart when required.
Maybe an extra parameter on the input message? or a unique parameter into a special msg? Get the simplest way.

Dynamic timeout will be VERY appreciated, making tuya-smart-device better!

Best regards
m.s.

**Comment by vinodsr** [comment]
Will include a dynamic timeout in the next release

**Comment by msillano** [comment]
Perfect, thanks... This is very good news, a way to freeze some devices is really mandatory.
This will make also it possible to mitigate performance problems: the tuya-cloud limits are  20 homes per user and 120 devices per home!

I found a new error message in  _tuya_smart_device node_  ver.2.0.0
````
       "Timeout waiting for status response from device id: bfa355aa196ae5975cy6ii"
````
Anyway, the rules are always the same: 
 - _error_ is that the user of _tuya_smart_device node_ MUST correct in own code, think about it as a blocking situation, a programming error  (e.g. missing Device key).
 - _info_  happens in runtime and it is an unusual but not blocking behavior. The user CAN  do actions to prevent this situation, but it is not mandatory (ignore strategy).

Do "Timeout waiting for status response" is a blocking situation in _tuya_smart_device node_ use?  if not, catch it, and do only info.

Idea:
-  Maybe it is better to send some ERROR/info messages in the output message, e.g. in msg.statusCode ?  Like _statusCode_ in HTTP request node, the block user can easily do actions based on it.

- As an alternative,  make all  _tuya_smart_device node_ errors/info [_catchable errors_](https://nodered.org/docs/user-guide/handling-errors#catchable-errors) so they can be caught by a catch node standard, i.e. use only the status and don't write any message to the log.

As a workaround, for now, I modified the code of tuyapi 6.1.1, but this is not a good way to do.

Best regards
m.s.

**Comment by cw-kid** [comment]
I am also having problems with it connecting and I see these errors:

"Error: find() timed out. Is the device powered on and the ID or IP correct?"

I only have one device on my Tuya account a Galaxy Star Projector Light. 

Sometimes it connects OK but a lot of the time it doesn't and I see that error. 

Thanks
