### ISSUE TITLE
can't connect with old protocol version and a fixup

### ISSUE THREAD

**Issue by kaeptnslow** [vinodsr/node-red-contrib-tuya-smart-device#39]
hello,

i'm not so familiar with GIT. So i apologize to deliver some changes via this post.

I had a relatively new tuya based device, which requires protocol version [3.3]
 Its not located in the same Subnet of my node red server.

To solve this problem i change the html and js file a bit.

- html: i added IP Input and Version Input
- Js: i changed the constructor to add IP and Version and do some checkup before

I'm not a JS crack. 

i would be happy if you could add the extension to the code base. I think that makes it more valuable.
kind regards
Kai

**Comment by kaeptnslow** [comment]
sorry, i cant files....here are the code directly:


**tuya-smart-device.html:**

`<script type="text/javascript">
    RED.nodes.registerType('tuya-smart-device', {
        category: 'smarthome',
        color: '#C7E9C0',
        defaults: {
            deviceName: { value: "", required: true },
            deviceId: { value: "", required: true },
            deviceKey: { value: "", required: true },
	    deviceIp: { value: "", required: false},
	    version: { value: "3.2", required: false}
        },
        inputs: 1,
        outputs: 1,
        icon: "bridge.svg",
        label: function () {
            return this.deviceName || "tuya smart device";
        }
    });
</script>

<script type="text/html" data-template-name="tuya-smart-device">
    <div class="form-row">
        <label for="node-input-deviceName"><i class="fa fa-tag"></i> Device Name</label>
        <input type="text" id="node-input-deviceName" placeholder="Bulb">
    </div>
    <div class="form-row">
        <label for="node-input-deviceIp"><i class="fa fa-id-card-o"></i> Device Virtual IP</label>
        <input type="text" id="node-input-deviceIp" placeholder="">
    </div>
    <div class="form-row">
        <label for="node-input-deviceId"><i class="fa fa-id-card-o"></i> Device Virtual ID</label>
        <input type="text" id="node-input-deviceId" placeholder="">
    </div>
    <div class="form-row">
        <label for="node-input-deviceKey"><i class="fa fa-key"></i> Device Key</label>
        <input type="text" id="node-input-deviceKey" placeholder="">
    </div>
    <div class="form-row">
        <label for="node-input-Version"><i class="fa fa-id-card-o"></i> Version</label>
        <input type="text" id="node-input-version" placeholder="3.1">
    </div>`

**tuya-smart-device.js**

`        this.deviceIp = config.deviceIp;
	     this.version  = config.version;
	     if (!config.deviceIp) config.deviceIp = "";
	     if (!config.version) config.version = 3.1;`

`        let tuyaDevice = new TuyaDevice({
            id: node.deviceId,
            key: node.deviceKey,
            issueGetOnConnect: false,
            nullPayloadOnJSONError: false,
	         ip: node.deviceIp,
            version: node.version
        });`

**Comment by vinodsr** [comment]
The code is not clear . Is it possible for you to submit a pull request ?

**Comment by kaeptnslow** [comment]
do i need an new branch to do this?

**Comment by vinodsr** [comment]
Understood the code . I am working on it.
