### ISSUE TITLE
Connecting to Tuya Device from Node Red in Docker Container

### ISSUE THREAD

**Issue by FreeTechNick** [vinodsr/node-red-contrib-tuya-smart-device#42]
Hi,

I can't connect to my tuya Device from Node Red in Docker Container. It is working from a Node Red directly installed on a Raspberry PI.

I added the Ports 

    - "6666:6666/udp"
    - "6667:6667/udp"
    - "6668:6668/udp"

to the container but with out success.

Any Tipp?

Thank you.
Markus

**Comment by vinodsr** [comment]
Can you provide more details about the docker setup ( wsl windows etc ?)

Also please check if you can try with tuya-cli get command.

**Comment by FreeTechNick** [comment]
I’m running it on a Raspberry Pi with IOTstack. NodeRed is run in a docker container. If the Tuya Client I get also no connection and get a TimeOut Error. Thanks.

**Comment by vinodsr** [comment]
Is this related to your issue ? 
https://github.com/TuyaAPI/cli/issues/37

Previously i had an issue with WSL  2 - ubuntu, where the tuya lookup using sockets gets blocked.

**Comment by FreeTechNick** [comment]
I was able to solve my problem. It was the above ports and only one client can access the Tuya device at a time.
