### ISSUE TITLE
"TypeError: config.retryTimeout.trim is not a function"

### ISSUE THREAD

**Issue by tstaddon** [vinodsr/node-red-contrib-tuya-smart-device#43]
Hi

I get this when I'm deploying; tuyapi 6.1.5 is installed. 

Tuyapi wizard is returning all devices correctly with no issues, as is TinyTuya (https://pypi.org/project/tinytuya/) so there is no problem on the client device, LAN or Tuya API side of things. Other plugins are working OK.

**Comment by vinodsr** [comment]
Can you please provide me a screenshot of the node edit window.

**Comment by fantastxu** [comment]
I get the same error here.
Below is the screenshot
![image](https://user-images.githubusercontent.com/2860633/107742936-d2259400-6cc4-11eb-8ee6-52c61722e88f.png)

**Comment by fantastxu** [comment]
I managed to make it connected, it seems the default "retry" and "find" values in the input trigger the error. You can not input the value directly, instead, you need to change the value using the little up/down arrow then the errors are gone. 

BTW, how can I get the smart plug energy monitor data like current mA, current W, current V, etc?

**Comment by vinodsr** [comment]
You will get the data in the payload under a dps key  emitted by the device. It is very particular to the device type. 

You can  try inject a get schema 

![image](https://user-images.githubusercontent.com/462648/107794480-81be3d00-6d7d-11eb-8034-2f7feef3a08b.png)

Let me know if it helps

**Comment by vinodsr** [comment]
@tstaddon  Can you please confirm the version of the node you are using . ? I am not able to replicate the error. 

But found another bug , not related to this one. :)

**Comment by fantastxu** [comment]
> You will get the data in the payload under a dps key emitted by the device. It is very particular to the device type.
> 
> You can try inject a get schema
> 
> ![image](https://user-images.githubusercontent.com/462648/107794480-81be3d00-6d7d-11eb-8034-2f7feef3a08b.png)
> 
> Let me know if it helps

![image](https://user-images.githubusercontent.com/2860633/107843658-fa26fd00-6d81-11eb-8286-67d38faa2adf.png)

It works like a charm, thanks. Then I need to figure out which dps represent which data....

**Comment by vinodsr** [comment]
> I managed to make it connected, it seems the default "retry" and "find" values in the input trigger the error. You can not input the value directly, instead, you need to change the value using the little up/down arrow then the errors are gone.
> 
> BTW, how can I get the smart plug energy monitor data like current mA, current W, current V, etc?

@fantastxu  any idea how to replicate this TypeError. I tried inputting the number using keyboard in to the fields, but can't see this error.  Are you using the latest version ?

**Comment by fantastxu** [comment]
1.create a new Flow
2. add Tuya node
3. deploy
4. got TypeError message

You can check the gif attachment for more details.

![screenrecord](https://user-images.githubusercontent.com/2860633/107859785-b5867a80-6df0-11eb-9a02-7715f97d51b0.gif)

My Note-RED version is 1.2.9

**Comment by vinodsr** [comment]
Thanks @fantastxu . Found the issue and fixed.

Right now i am away from home. Will test with the devices and publish later today.

**Comment by vinodsr** [comment]
Published Version 3.0.2 that fixes this issue. Please try and let me know.

**Comment by vinodsr** [comment]
Thanks @fantastxu  for the excellent support and @tstaddon  for reporting .

**Comment by fantastxu** [comment]
> Published Version 3.0.2 that fixes this issue. Please try and let me know.

Just tried and all are working flawlessly.

**Comment by fantastxu** [comment]
> Thanks @fantastxu for the excellent support and @tstaddon for reporting .

I am glad that I can help. Your project is very useful to us. Please keep up the great work!
