### ISSUE TITLE
Timeout at generic node

### ISSUE THREAD

**Issue by ammawel** [vinodsr/node-red-contrib-tuya-smart-device#49]
Hello,
the device-node works fine for me. However, I get error messages in 3 out of 10 cases with the generic node:

> An error had occured : find() timed out. Is the device powered on and the ID or IP correct?

or

> An error had occured : Error: Error from socket
> An error had occured : Timeout waiting for status response from device id:XXXXXXX
> 

Of course the device is powered on and the IP or ID are correct; a ping from the raspberry with node-red to the device works fine and stable. It makes no difference if you use  ID or IP.
Thanks for any help,
Achim

**Comment by vinodsr** [comment]
Can you please share the payload used. 

> You can mask the device ID or any sensitive information

**Comment by ammawel** [comment]
Here is one payload:
```
{
    "deviceVirtualId": "XXXXX",
    "deviceKey": "XXXXX",
    "operation": "SET",
    "payload": {
        "dps": 20,
        "set": true
    }
}
```
I also tried "deviceIp": "XXX" instead of ID or inserted "version": "3.3"; it makes no difference.

**Comment by zhaokgithub** [comment]
@amma

> Here is one payload:
> 
> ```
> {
>     "deviceVirtualId": "XXXXX",
>     "deviceKey": "XXXXX",
>     "operation": "SET",
>     "payload": {
>         "dps": 20,
>         "set": true
>     }
> }
> ```
> 
> I also tried "deviceIp": "XXX" instead of ID or inserted "version": "3.3"; it makes no difference.

I had the same problem

**Comment by vinodsr** [comment]
Can you please share the logs . 

have you set the payload as 

msg.payload = {
    "deviceVirtualId": "XXXXX",
    "deviceKey": "XXXXX",
    "operation": "SET",
    "payload": {
        "dps": 20,
        "set": true
    }
}

**Comment by ammawel** [comment]
@zhaokgithub 
No errors for me since the last update to version 4.0.1 or Tuya 7.1
Can the thread be closed?

**Comment by zhaokgithub** [comment]
> @zhaokgithub
> No errors for me since the last update to version 4.0.1 or Tuya 7.1
> Can the thread be closed?

Ok,thanks
