### ISSUE TITLE
TypeError: ID and IP are missing from device

### ISSUE THREAD

**Issue by antonio1000homens** [vinodsr/node-red-contrib-tuya-smart-device#50]
I'm using the generic node to pass on the device details via parameters however I keep getting this message
TypeError: ID and IP are missing from device

![image](https://user-images.githubusercontent.com/36929120/113894652-20847a00-97c0-11eb-9183-2c693b2a324b.png)

Am I doing anything silly?

**Comment by vinodsr** [comment]
Don't pass ID and IP at once. Pass either one of it at a time.

**Comment by antonio1000homens** [comment]
Yes Tried that also using one or another.. 
Are you using this node without errors?

**Comment by vinodsr** [comment]
Can you please confirm the version?

Is it possible for you tot share the logs ?

**Comment by antonio1000homens** [comment]
Ok my bad, if this can help anyone the "payload" is actually nested inside another payload.. 
so where I configured
{ 
       "deviceID":"..."
       "payload": {"dps":"1"...}
}

should have been

{
"payload":{ 
       "deviceID":"..."
       "payload": {"dps":"1"...}
        }
}

So yeah was doing something Silly! Thanks for the help!
