### ISSUE TITLE
Data is in binary not JSON

### ISSUE THREAD

**Issue by csmale** [vinodsr/node-red-contrib-tuya-smart-device#61]
I am working with a Gosund LB3 bedside lamp. I have it all connected and when I switch it on and off, or change the settings, I get an event as expected. But payload.data contains a string full of gibberish - except I can recognise "3.3" as the first three characters.

`{"log":"9 May 11:28:33 - [info] [tuya-smart-device:Colin Bed] Data from device  [event:data]: \"3.3\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0000\\u0012\\u0000\\u0000\\u0000\\u0001x��M�ל\\u0014��S~(����=|�}c����I\\u0017L/\\u0013���ʛ���hu��`��ÚR\\u0015��\\u0000VA�\\b/P\\u0015�a\\u0019��[t�룠���j�_\\u000e�\"\n","stream":"stdout","time":"2021-05-09T09:28:33.967091852Z"}`

Does anyone have any idea what is going on here?
I have tried to look at the data in binary, but as it is contained in a string, loads of values get converted to 0xfffd so I can't really analyse it like that. I end up with (might not be the exact same message as above):
```
0033 002e 0033 0000 0000 0000 0000 0000 0000 0000 0012 0000 0000 0000 0001 0078 fffd fffd 004d fffd 05dc 0014 fffd fffd 0053 007e 0028 fffd fffd fffd fffd 003d 007c fffd 007d 0063 fffd fffd fffd fffd 0049 0017 0
04c 002f 0013 fffd fffd fffd 029b fffd fffd fffd 0068 0075 fffd fffd 0060 fffd fffd 00da 0052 0015 fffd fffd 0000 0056 0041 fffd 0008 002f 0050 0015 fffd 0061 0019 fffd fffd 005b 0074 fffd b8e0 fffd fffd fffd 00
6a fffd 005f 000e fffd
```

**Comment by msillano** [comment]
In my experiece this is caused always by bad Key. 
This happens also when you disconnect and reconnect a [device to tuya](https://github.com/codetheweb/tuyapi#-notes). Redo  "`tuya-cli wizard`" and update the key in `tuya-smart-device` node. Example: see [ISSUE#407](https://github.com/codetheweb/tuyapi/issues/407#issue-787530319).
Double check the values used.

Best regards
m.s.
