### ISSUE TITLE
Feature: Instructions for getting the device id

### ISSUE THREAD

**Issue by Matten-Matten** [vinodsr/node-red-contrib-tuya-smart-device#65]
1.  open: https://iot.tuya.com/index/ and LogIn
2.  -> Cloud
3.  -> API Explorer (https://iot.tuya.com/cloud/explorer)
4.  ->Data Center: Europe
5.  -> Get device details
6.  -> insert device_id
7.  -> submit request

"ta...da..."

the local_key!

```
{
  "result": {
    "active_time": ,
    "biz_type": ,
    "category": "",
    "create_time": ,
    "icon": "smart/icon/....jpg",
    "id": "",
    "ip": "",
    "lat": "",
->  "local_key": "xxxxxxxxx",
    "lon": "",
    "name": "",
    "online": true,
    "owner_id": "",
    "product_id": "",
    "product_name": "",
    "status": [],
    "sub": ,
    "time_zone": "",
    "uid": "",
    "update_time": ,
    "uuid": ""
  },
  "success": true,
  "t": 
}
```
![datacenter](https://user-images.githubusercontent.com/32074970/120865688-cff68680-c58e-11eb-8b79-cbe9c0b38712.png)
![datacenter 2](https://user-images.githubusercontent.com/32074970/120865687-cf5df000-c58e-11eb-9611-47d40a934302.png)

Gruß
Matten Matten

**Comment by vinodsr** [comment]
Can you please submit this as a PR.
