### ISSUE TITLE
Getting a cryptic output from Device

### ISSUE THREAD

**Issue by DeadlyVirez** [vinodsr/node-red-contrib-tuya-smart-device#70]
Sorry, I'm a bit new to this but I've double checked, that every value is correct (IP, Key, ID)

I'm getting this output when I'm setting the switch to off/on via the Tuya App.

I'm using Gosund Devices SP211 (I think.)

![grafik](https://user-images.githubusercontent.com/24830874/123380266-87c7f400-d58f-11eb-9d19-3f2b86ac0f32.png)

**Comment by craigcurtin-dev** [comment]
Just a hint to try it as V 3.1 and see if you get the same result

Craig

**Comment by DeadlyVirez** [comment]
Yes, I'm getting the error on 3.1, too

![grafik](https://user-images.githubusercontent.com/24830874/123379525-8f3acd80-d58e-11eb-8259-90dc2580a6f4.png)

**Comment by craigcurtin-dev** [comment]
Hang on - you haven't filled in both the IP and device ID have you ?

**Comment by DeadlyVirez** [comment]
I know that it clearly states NOT to do that.
I tried both ways, just using the ID or the IP but it can't find the device. see below.

![grafik](https://user-images.githubusercontent.com/24830874/123387236-da0d1300-d597-11eb-8553-4d558e625a3f.png)

If however, I fill both fields, it works instantly. I get responses back when I turn on/off the plug but get the cryptic message above.

**Comment by 8xiom** [comment]
Same here. Filling either IP address or Device Virtual ID results in "find() timed out". Double checked the device key which should be correct. If I change the last character of that key a different error immediately pops up. Then I filled both fields (device ID plus IP) and voilà, connection established. But, I not only receive these cryptic output. Unfortunately it's also not possible to issue commands to my device. This results in an error and a broken connection. So I guess something is wrong with the Tuya node in general.

**Comment by craigcurtin-dev** [comment]
Sorry but i am no expert on this one - i have just finished setting up my Heat Pump with it and it is working fine.

I went through a number of different nodes before i settled on this one.

One thing i did notice is that the install/uninstall of a number of nodes left behind some crap in NPM. When i moved it to a new machine and installed just this node into NR then all was OK.

I wonder if you have some leftover stuff from your experimenting ?

It might be an idea to uninstall this node, then go to the command line and make sur tuyapi is also removed, then restart the device (Assume RPi ?) and check from the commandline what is running and if there are any leftovers in NPM again ?

Craig

**Comment by hannoverRed** [comment]
Hi there,

is the device one thing about
1. Wifi connected to Smart Life
2. Zigbee or Bluetooth device connected via Gatweway
connected to Smart Life?

then this could help you!
Take the IP address of the gateway and then see if you get an output with CID. That would be the ID for the device behind a gateway.

[solution](https://github.com/vinodsr/node-red-contrib-tuya-smart-device/issues/80#issuecomment-1070339326)
