### ISSUE TITLE
IP Camera Motion detection - "json obj data unvalid"

### ISSUE THREAD

**Issue by dos-ise** [vinodsr/node-red-contrib-tuya-smart-device#72]
Hi,

first of all I would like to thank you for this cool project.

I am using a tuya IP camera and would like to trigger an event if motion is deteced.

Unfortunately I also have the problem that the device returns "json obj data unvalid" if I try to get the schema.

Is there a another way to get the list of dps or an event?

![image](https://user-images.githubusercontent.com/20043350/127766305-04202905-8449-489f-bf2f-23f61b186a32.png)

**Comment by vinodsr** [comment]
json unvalid is a known issue #14  .

Can you double check that either ip or vitual id is used. ?
