### ISSUE TITLE
Control Bulbs or get what commands i can use ?

### ISSUE THREAD

**Issue by Askeshine** [vinodsr/node-red-contrib-tuya-smart-device#76]
Hi i have use this contrib rlly amazing but i only can TURN OFF AND ON bulb...

I don't understand the "DPS" part

My bulb information show this: 
![imagen](https://user-images.githubusercontent.com/37356127/147907745-d04556d5-bd9d-47ab-b8a1-8a8ac32b0e0d.png)

Where i can see what its DPS and WHY dps ? -.- idk how to change color or other thing.

**Comment by vinodsr** [comment]
DPS are index numbers which controls the behavior of the device using the tuyaAPI. 

eg: dps 1 normally controls the power, so setting dps as 1 and set variable as true will turn on the bulb

the dps index differs from device to device. 

To see the dps for your device, connect a debug node to the output of the tuya-smart-device node, turn the bulb on / off using the app. you can see the output in the debug panel . similarly you can check with change color , brightness etc.
