### ISSUE TITLE
Allow "Device Key" to be specified as a secret

### ISSUE THREAD

**Issue by foxylion** [vinodsr/node-red-contrib-tuya-smart-device#77]
Hi,
I added some tuja nodes to my flows, but I noticed that the tuya nodes store the "Device Key" within the `flow.json` file.
This has the negative side effect that I can no longer publish this file into a Git repository as I would store secrets into the repository.

Is it possible that the tuya nodes store the secret into the `flows_cred.json` file?
See https://nodered.org/docs/creating-nodes/credentials for details.

**Comment by vinodsr** [comment]
> Hi,
> 
> I added some tuja nodes to my flows, but I noticed that the tuya nodes store the "Device Key" within the `flow.json` file.
> 
> This has the negative side effect that I can no longer publish this file into a Git repository as I would store secrets into the repository.
> 
> 
> 
> Is it possible that the tuya nodes store the secret into the `flows_cred.json` file?
> 
> See https://nodered.org/docs/creating-nodes/credentials for details.

Thanks for the feedback. Let me check the feasibility of this. I don't want to break the current working model as well.

**Comment by foxylion** [comment]
Hi, this feature would still be helpful!

**Comment by foxylion** [comment]
As previously said. I would still love to see this feature.  :-)

**Comment by vinodsr** [comment]
@foxylion 

After checking the compatibility , i am planning to introduce a check box "Store as credentials" which will store the deviceId and deviceKey in the credentials file. 

This will give flexibility as some users still want to store the id in the flows file so that they can easily import export. 

Hope this will serve your request. 

I had started the development of this.

**Comment by foxylion** [comment]
@vinodsr that would be awesome! Really appreciate it :)

**Comment by vinodsr** [comment]
Released Version 5.0.0 Please check and let me  know .

**Comment by foxylion** [comment]
@vinodsr I just checked it. Works perfectly, thank you!
