### ISSUE TITLE
Tuya IoT Platform Virtual Device

### ISSUE THREAD

**Issue by hannoverRed** [vinodsr/node-red-contrib-tuya-smart-device#81]
Hello, everyone,

when I create a virtual device on the Tuya IoT Platform.
Can I get an ID and a KEY for this device.
Since it is a virtual one, it has NO ip address.
when I enter the ID and the KEY in the node I get no connection.
is there a solution for this?

lg

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/60238337/159171560-d8dc043e-71af-48cd-b3f2-593e485f5752.png">

**Comment by Saimond** [comment]
Hi;
I'm having a problem with virtual devices..

I came to this site:
[Tuya Developers](https://iot.tuya.com/cloud/explorer?id=p16480536740103tqvv3&groupId=group-home&interfaceId=470224448454738#ResultObject)

got the ID and Local_Key

But in NodeRed, this is the result:

![Captura de Tela 2022-03-26 às 04 15 55](https://user-images.githubusercontent.com/12146537/160229273-1caf260f-7de6-4693-a08c-8dce7fc8fdce.png)
![Captura de Tela 2022-03-26 às 04 16 31](https://user-images.githubusercontent.com/12146537/160229279-93eb1fa1-3ff1-4f66-8905-73640d8706de.png)

Is it possible to use virtual devices?

So, I can add devices that do not contain Tuya..

Thank you!

**Comment by hannoverRed** [comment]
> Hi; I'm having a problem with virtual devices..
> 
> I came to this site: [Tuya Developers](https://iot.tuya.com/cloud/explorer?id=p16480536740103tqvv3&groupId=group-home&interfaceId=470224448454738#ResultObject)
> 
> got the ID and Local_Key
> 
> But in NodeRed, this is the result:
> 
> ![Captura de Tela 2022-03-26 às 04 15 55](https://user-images.githubusercontent.com/12146537/160229273-1caf260f-7de6-4693-a08c-8dce7fc8fdce.png) ![Captura de Tela 2022-03-26 às 04 16 31](https://user-images.githubusercontent.com/12146537/160229279-93eb1fa1-3ff1-4f66-8905-73640d8706de.png)
> 
> Is it possible to use virtual devices?
> 
> So, I can add devices that do not contain Tuya..
> 
> Thank you!

Hi there,

What kind of virtual device is that? a device that you learned via a HUB/gateway?
enter the IP address (NOT THE ID) of the gateway and the gateway KEY.

After that, when the connection is established, switch on the virtual device in the Tuya/SmartLife APP and see which data points the node provides you with.
