### ISSUE TITLE
Incoming message Outgoing message

### ISSUE THREAD

**Issue by hannoverRed** [vinodsr/node-red-contrib-tuya-smart-device#82]
Hello everyone,

could you get the function that if you send a message to the node, it doesn't output a message.
but only a message output if no input value came before?

lg

**Comment by msillano** [comment]
This cannot be a general rule: many DPs change on their own under various circumstances.

But it is easy do it for some DPs, if required, using 2 more nodes. Example:
     1. device output: Strore in the flow the reponse msg, e.g. in 'last-data': `flow.set("last-data", msg);`
     2. device input: Test 'last-data' before  to send any message:
´``
          if (env.get('last-data' ) === undefined)
                   send(message).
`´`
 So the message is sent to device one and only one time.

Enjoy

**Comment by hannoverRed** [comment]
do you have an example flow?

**Comment by msillano** [comment]
![Immagine 2022-04-10 110339](https://user-images.githubusercontent.com/26389457/162611000-a74ed9c3-4828-4dd9-b626-d11f5138b82b.png)
Code function node 'check':
```
if (flow.get("last data"))
    return null;
return msg;
```
Code function node 'store'
```
//example:  only for DP 5
if(msg.payload.data.dps[5])
   flow.set("last-data", msg);
return msg;
```
enjoy
m.s.

**Comment by hannoverRed** [comment]
Hi, thanks for the tip. but that doesn't change the value. True False
