### ISSUE TITLE
Device never found via virtual id or with IP address?

### ISSUE THREAD

**Issue by Jibun-no-Kage** [vinodsr/node-red-contrib-tuya-smart-device#85]
Device never found via virtual id or with IP address?

msg : Object
object
context: object
message: "Error: find() timed out. Is the device powered on and the ID or IP correct?"
deviceVirtualId: "[redacted]"
deviceIp: ""
deviceKey: "[redacted]"
error: object
message: "find() timed out. Is the device powered on and the ID or IP correct?"
source: object
_msgid: "a944fa34e6e5bc60"

I used tuya-cli wizard, to get the key, got virtual id from smart app device configuration.  Device is ping-able and tuya phone app can control the device without issue.  So not sure what to try next?

MAC address is correct and can see it in ARP, so the device is visible from the Node Red hosting device.

**Comment by vinodsr** [comment]
Is the Tuya Cli installed in the same machine as node red ? 

Can you try giving the IP instead of ID ?

**Comment by vinodsr** [comment]
Can you try IP instead of ID?

**Comment by Jibun-no-Kage** [comment]
Sorry I decided to keep using the nodes I now have working.
